
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { CircuitBoard, ZoomIn, ZoomOut, Power } from 'lucide-react';

const CircuitVisualization: React.FC = () => {
  const [zoom, setZoom] = useState(1);
  
  const increaseZoom = () => setZoom(prev => Math.min(prev + 0.2, 3));
  const decreaseZoom = () => setZoom(prev => Math.max(prev - 0.2, 0.5));
  
  return (
    <div className="h-full flex flex-col border-l border-border">
      <div className="flex items-center justify-between border-b border-border p-2 bg-card">
        <div className="flex items-center gap-2">
          <CircuitBoard className="h-5 w-5 text-electric-light" />
          <span className="font-medium">Circuit Simulator</span>
        </div>
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon" onClick={decreaseZoom}>
            <ZoomOut size={16} />
          </Button>
          <span className="text-sm min-w-8 text-center">{Math.round(zoom * 100)}%</span>
          <Button variant="ghost" size="icon" onClick={increaseZoom}>
            <ZoomIn size={16} />
          </Button>
        </div>
      </div>
      
      <Tabs defaultValue="schematic" className="flex flex-col flex-1">
        <TabsList className="bg-card border-b border-border rounded-none px-2">
          <TabsTrigger value="schematic" className="data-[state=active]:bg-electric-dark data-[state=active]:text-electric-light">Schematic</TabsTrigger>
          <TabsTrigger value="analysis" className="data-[state=active]:bg-electric-dark data-[state=active]:text-electric-light">Analysis</TabsTrigger>
        </TabsList>
        
        <TabsContent value="schematic" className="flex-1 p-4 overflow-auto grid-bg">
          <div className="flex items-center justify-center h-full">
            <div 
              className="border border-dashed border-electric p-8 rounded-lg bg-background/50 transform transition-transform"
              style={{ transform: `scale(${zoom})` }}
            >
              <div className="flex flex-col items-center gap-4">
                <div className="oscilloscope-glow">
                  <CircuitBoard size={100} className="text-electric-green" />
                </div>
                <p className="text-center text-sm text-muted-foreground max-w-xs">
                  Circuit schematic will be displayed here when generated by the AI assistant.
                  Ask about a specific circuit to see its diagram.
                </p>
                <Button variant="outline" className="border-electric text-electric-light">
                  <Power size={16} className="mr-2" />
                  Simulate Circuit
                </Button>
              </div>
            </div>
          </div>
        </TabsContent>
        
        <TabsContent value="analysis" className="flex-1 p-4 overflow-auto grid-bg">
          <div className="flex items-center justify-center h-full">
            <div className="border border-dashed border-electric-cyan p-8 rounded-lg bg-background/50">
              <div className="flex flex-col items-center gap-4">
                <div className="w-64 h-32 bg-electric-dark/70 rounded-lg overflow-hidden border border-electric-cyan oscilloscope-glow flex items-center justify-center">
                  <div className="w-full h-full relative">
                    <div className="absolute inset-0 flex items-center">
                      <div className="w-full h-px bg-electric-green/50"></div>
                    </div>
                    <div className="absolute inset-0 flex flex-col justify-center">
                      <div className="w-full h-px bg-electric-green/50"></div>
                      <div className="w-full h-px bg-electric-green/50 mt-8"></div>
                      <div className="w-full h-px bg-electric-green/50 -mt-8"></div>
                    </div>
                    <svg className="w-full h-full" viewBox="0 0 100 50">
                      <path 
                        d="M 0,25 Q 15,10 25,25 T 50,25 T 75,25 T 100,25" 
                        fill="none" 
                        stroke="#10B981" 
                        strokeWidth="1"
                      />
                    </svg>
                  </div>
                </div>
                <p className="text-center text-sm text-muted-foreground max-w-xs">
                  Circuit analysis plots will be displayed here when generated by the AI assistant.
                  Ask for voltage, current, or frequency analysis to see corresponding plots.
                </p>
              </div>
            </div>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default CircuitVisualization;
