
import { CircuitBoard } from 'lucide-react';

const CircuitVisualization: React.FC = () => {
  return (
    <div className="h-full flex flex-col border-l border-border">
      <div className="flex items-center justify-between border-b border-border p-2 bg-card">
        <div className="flex items-center gap-2">
          <CircuitBoard className="h-5 w-5 text-electric-light" />
          <span className="font-medium">Circuit Visualization</span>
        </div>
      </div>
      
      <div className="flex-1 p-4 overflow-auto grid-bg">
        <div className="flex items-center justify-center h-full">
          <div className="border border-dashed border-electric p-8 rounded-lg bg-background/50">
            <div className="flex flex-col items-center gap-4">
              <div className="oscilloscope-glow">
                <CircuitBoard size={100} className="text-electric-green" />
              </div>
              <p className="text-center text-sm text-muted-foreground max-w-xs">
                Circuit visualization will appear here when generated by the AI assistant.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CircuitVisualization;
